name: Go
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release-linux-arm:
    name: release linux/386
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: compile and release
      uses: flobz/go-release.action@v1.0.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: "arm"
        GOOS: linux
        PROJECT_NAME: modbus-cli
