name: Go
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release-linux-arm:
    name: release linux/386
    runs-on: ubuntu-latest
    steps:
    - name: compile and release
      uses: ngs/go-release.action@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOARCH: "arm"
        GOOS: linux
